require "html"
require "../models/result"
require "../utils/version"
require "./reporter"

module Authz0
  module Report
    # Self-contained HTML report (inline CSS, no external assets). Findings are
    # highlighted; the table is sortable-looking but static — it's meant for
    # sharing a single file.
    class HtmlReport
      def render(results : Array(Result)) : String
        summary = Summary.new(results)
        String.build do |io|
          io << "<!doctype html>\n<html lang=\"en\">\n<head>\n"
          io << "<meta charset=\"utf-8\">\n"
          io << "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
          io << "<title>authz0 report</title>\n"
          io << style
          io << "</head>\n<body>\n"
          io << "<header><h1>authz0 <span class=\"v\">v#{Authz0::VERSION}</span></h1>"
          io << "<p class=\"sub\">authorization scan report</p></header>\n"

          io << "<section class=\"cards\">\n"
          card(io, "targets", summary.targets.to_s, "n")
          card(io, "probes", summary.total.to_s, "n")
          card(io, "unauthorized", summary.unauthorized.to_s, summary.unauthorized > 0 ? "bad" : "good")
          card(io, "over-restrictive", summary.over_restrictive.to_s, summary.over_restrictive > 0 ? "warn" : "n")
          card(io, "errors", summary.errors.to_s, summary.errors > 0 ? "warn" : "n")
          io << "</section>\n"

          io << "<table>\n<thead><tr>"
          %w[# Status Method Target Role Access Expected RLT Reason].each { |h| io << "<th>" << h << "</th>" }
          io << "</tr></thead>\n<tbody>\n"
          results.each { |r| row(io, r) }
          io << "</tbody>\n</table>\n"
          io << "<footer>generated by authz0 v#{Authz0::VERSION}</footer>\n"
          io << "</body>\n</html>\n"
        end
      end

      private def card(io, label, value, kind)
        io << "<div class=\"card #{kind}\"><div class=\"val\">" << HTML.escape(value)
        io << "</div><div class=\"lbl\">" << HTML.escape(label) << "</div></div>\n"
      end

      private def row(io, r : Result)
        cls = case r.severity
              in Result::Severity::High then " class=\"finding\""
              in Result::Severity::Low  then " class=\"over\""
              in Result::Severity::None then (r.verdict == "?" ? " class=\"unknown\"" : "")
              end
        status = r.error ? "ERR" : r.status_code.to_s
        target = r.alias && !r.alias.try(&.empty?) ? r.alias.to_s : r.url
        io << "<tr" << cls << ">"
        cell(io, "#" + r.index.to_s)
        cell(io, status)
        cell(io, r.method)
        cell(io, target)
        cell(io, r.display_role)
        cell(io, r.accessible ? "yes" : "no")
        cell(io, r.verdict == "?" ? "—" : (r.expected_access ? "yes" : "no"))
        cell(io, r.verdict)
        cell(io, r.reason)
        io << "</tr>\n"
      end

      private def cell(io, value : String)
        io << "<td>" << HTML.escape(value) << "</td>"
      end

      private def style : String
        <<-CSS
        <style>
        :root{--bg:#0d1117;--fg:#e6edf3;--mut:#8b949e;--line:#30363d;--bad:#f85149;--good:#3fb950;--warn:#d29922}
        *{box-sizing:border-box}
        body{margin:0;font:14px/1.5 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;background:var(--bg);color:var(--fg)}
        header{padding:24px 28px;border-bottom:1px solid var(--line)}
        h1{margin:0;font-size:22px}.v{color:var(--mut);font-weight:400;font-size:14px}
        .sub{margin:4px 0 0;color:var(--mut)}
        .cards{display:flex;gap:14px;flex-wrap:wrap;padding:20px 28px}
        .card{background:#161b22;border:1px solid var(--line);border-radius:10px;padding:14px 18px;min-width:110px}
        .card .val{font-size:26px;font-weight:700}.card .lbl{color:var(--mut);text-transform:uppercase;font-size:11px;letter-spacing:.05em}
        .card.bad .val{color:var(--bad)}.card.good .val{color:var(--good)}.card.warn .val{color:var(--warn)}
        table{width:calc(100% - 56px);margin:8px 28px 28px;border-collapse:collapse;font-size:13px}
        th,td{text-align:left;padding:8px 10px;border-bottom:1px solid var(--line);vertical-align:top}
        th{color:var(--mut);text-transform:uppercase;font-size:11px;letter-spacing:.04em}
        tr.finding{background:rgba(248,81,73,.12)}tr.finding td:last-child{color:var(--bad)}
        tr.over{background:rgba(210,153,34,.10)}tr.over td:last-child{color:var(--warn)}
        tr.unknown{background:rgba(139,148,158,.10)}
        td:nth-child(4){max-width:420px;word-break:break-all}
        footer{padding:18px 28px;color:var(--mut);border-top:1px solid var(--line)}
        </style>
        CSS
      end
    end
  end
end
