---
name: CI
on:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/ci.yml
      - shard.yml
      - shard.lock
      - docker/Dockerfile
      - "**/*.cr"
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      logLevel:
        description: manual run
        required: false
        default: ""
jobs:
  build-crystal:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crystal-version: [1.19.0, 1.20.0]
    steps:
      - uses: actions/checkout@v6
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal-version }}
      - name: Install dependencies
        run: shards install
      - name: Build
        run: shards build
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: crystal-lang/install-crystal@v1
      - name: Check formatting
        run: crystal tool format --check src spec
      - name: Run Ameba linter
        uses: crystal-ameba/github-action@v0.9.0
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crystal-version: [1.19.0, 1.20.0]
    steps:
      - uses: actions/checkout@v6
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal-version }}
      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec
  build-docker:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: linux/amd64
            runner: ubuntu-latest
          - arch: linux/arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Build Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.arch }}
          cache-from: type=gha,scope=${{ matrix.arch }}
          cache-to: type=gha,mode=max,scope=${{ matrix.arch }}
  build-snapcraft:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        platform: [amd64]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6
      - name: Build snapcraft package
        uses: canonical/action-build@v1
        id: build
